# Generated by Django 4.0.3 on 2022-05-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.DeleteModel(
            name='Drop',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
